name: Create guru cards

on:
  push:
    branches:
      - master

jobs:
  guru:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs commands using the runners shell
      - name: Run the update markdown script
        run: |
          node update_markdown.js
      - name: Commit files after updating markdown script
        run: |
          git config --local user.name "asyi"
          git config --local user.email "alsery@protonmail.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Updating the README file with a unique tag"
          git push
          git pull --no-rebase
      - name: Run github-to-guru integration
      - name: Commit files for last time
        run: |
          git config --local user.name "asyi"
          git config --local user.email "alsery@protonmail.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Last update"
          git push
          git pull --no-rebase
        uses: partnerstack/github-to-guru@master
        env:
          GURU_USER_EMAIL: "${{ secrets.GURU_USER_EMAIL }}"
          GURU_USER_TOKEN: "${{ secrets.GURU_USER_TOKEN }}"
          GURU_COLLECTION_ID: "${{ secrets.GURU_COLLECTION_ID }}"
          GURU_COLLECTION_YAML: "collections/collection.yaml"
          GURU_TEAM_ID: "${{ secrets.GURU_TEAM_ID }}"
          GURU_CARD_YAML: "cards.yaml"
