name: Create guru cards

on:
  push:
    branches:
      - master

jobs:
  guru:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs commands using the runners shell
      - name: Run the build markdown script
        run: |
          node update_markdown.js # This file reads a few json files and then creates a set of html files in the doc folder
      - name: Commit files # transfer the new html files back into the repository
        run: |
          git add .
          git commit -m "Updating the README file with a unique tag"
          git push
      - name: Run github-to-guru integration
        uses: partnerstack/github-to-guru@master
        env:
          GURU_USER_EMAIL: "${{ secrets.GURU_USER_EMAIL }}"
          GURU_USER_TOKEN: "${{ secrets.GURU_USER_TOKEN }}"
          GURU_COLLECTION_ID: "${{ secrets.GURU_COLLECTION_ID }}"
          GURU_COLLECTION_YAML: "collections/collection.yaml"
          GURU_TEAM_ID: "${{ secrets.GURU_TEAM_ID }}"
          GURU_CARD_YAML: "cards.yaml"
